### ISSUE TITLE
When are chatrooms available?

### ISSUE THREAD

**Issue by WombatPete** [RetroShare/ChatServer#2]
I've recently downloaded Retroshare; I love the idea and I'm reading up and working on getting it all to work.
I've been watching https://retroshare.rocks/ ... but none of the chatrooms has been on-line yet; it's been the better part of a day.
Not sure what my expectations should be. Are they usually up? Or is it a rarity you have to hope to catch?

**Comment by myfingerhurt** [comment]
As far as I know, and my retroshare indicates that at least the telecomix is online, Check your NAT and DHT indicators which should be green,  and one of most important thing, you need to sign up your certificate to the chatserver. Did you do that?

**Comment by WombatPete** [comment]
I suspected as much, and I'm now sufficiently linked to see what you're saying. When I posted it, I meant that https://retroshare.rocks/ constantly shows them as being offline. Which is still true now. Perhaps that site, which is linked to on lots of Retroshare wiki/instruction pages, isn't working correctly?

**Comment by cavebeat** [comment]
https://retroshare.rocks/ <-- telecomix should be fixed. it's listed as online at rs.rocks and and i can confirm the server is also online in my friendlist. 

chatasaurus is off, and probably come online again. pirateparty is off and won't be online again.
